using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using SongDiary.Models;

namespace SongDiary.Data
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser> // Use your custom ApplicationUser
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public DbSet<EntryModel> Entries { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<EntryModel>()
                .Property(e => e.Id)
                .ValueGeneratedOnAdd(); // Indicate that Id will be generated by the database

            // Define the relationship with the ApplicationUser entity
            modelBuilder.Entity<EntryModel>()
                .HasOne(e => e.User) // Set the navigation property
                .WithMany(u => u.Entries) // Reference the collection in ApplicationUser
                .HasForeignKey(e => e.UserId) // Set the foreign key
                .OnDelete(DeleteBehavior.Cascade); // Adjust delete behavior if necessary
        }
    }
}

